{{/* Preprocess values and prepare config file */}}
{{- define "mumble.preprocess" -}}
controllers:
  main:
    containers:
      main:
        image:
          {{- toYaml .Values.image | nindent 10 }}

persistence:
  cert:
    name: {{ $.Release.Name }}-cert
    enabled: {{ .Values.certificate.enabled }}

secrets:
  config:
    stringData:
      murmur.ini: |
        {{- tpl .Values.config (merge .Values.configVars (dict "certEnabled" .Values.certificate.enabled)) | nindent 8 }}

{{- end -}}
{{- $_ := merge .Values (include "mumble.preprocess" . | fromYaml) -}}

{{/* Render the templates */}}
{{- include "bjw-s.common.loader.all" . }}
