{{- include "bjw-s.common.loader.init" . }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}
  labels:
    {{- include "bjw-s.common.lib.metadata.allLabels" . | nindent 4 }}
rules:
  - apiGroups:
      - apps
      - extensions
    resources:
      - deployments
      - daemonsets
      - statefulsets
    verbs:
      - list
      - get
      - patch
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}
  labels:
    {{- include "bjw-s.common.lib.metadata.allLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}
---
