#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
#

domains:
  example.com:
    enabled: false
    refreshSchedule: "0 2 * * *"
    sourceDomain: src.example.com
    sourcePort: 443
    privateKey: |-
      -----BEGIN RSA PRIVATE KEY-----
      BLAHBLAHBLAH
      -----END RSA PRIVATE KEY-----


containerConfig:
  securityContext:
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
  image:
    repository: ghcr.io/juniorjpdj/containers/openssl-kubectl
    tag: 1.34.2-r9@sha256:38627252ce2c10fe76d5efc889660c95d32be8f6bbf6ff9ba880fa4db9aac605
    pullPolicy: Always

serviceAccount:
  cert-puller: {}