#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
#

domains:
  example.com:
    enabled: false
    refreshSchedule: "0 2 * * *"
    sourceDomain: src.example.com
    sourcePort: 443
    privateKey: |-
      -----BEGIN RSA PRIVATE KEY-----
      BLAHBLAHBLAH
      -----END RSA PRIVATE KEY-----


containerConfig:
  securityContext:
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
  image:
    repository: ghcr.io/juniorjpdj/containers/openssl-kubectl
    tag: 1.34.2-r14@sha256:fa78052ee70bd0cc0a53f1129a02b671815ca88e6848b862ad4338380d500302
    pullPolicy: Always

serviceAccount:
  cert-puller: {}
