apiVersion: v2
name: deluge
description: Deluge is a lightweight, Free Software, cross-platform BitTorrent client.
type: application
version: 0.1.18
appVersion: 2.0.3
kubeVersion: ">=1.22.0-0"
keywords:
  - deluge
  - torrent
  - bittorrent
  - download
  - seedbox
  - seed
  - networking
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 3.7.2
sources:
  - https://git.deluge-torrent.org/deluge
  - https://github.com/divadsn/docker-deluge-ltconfig
  - https://github.com/JuniorJPDJ/charts/tree/master/charts/deluge
annotations:
  artifacthub.io/links: |-
    - name: App Webpage
      url: https://deluge-torrent.org/
    - name: App Source
      url: https://git.deluge-torrent.org/deluge
    - name: Dockerfile Source
      url: https://github.com/divadsn/docker-deluge-ltconfig
    - name: Chart Source
      url: https://github.com/JuniorJPDJ/charts/tree/master/charts/deluge
