#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
#

image: 
  repository: divadsn/deluge-ltconfig
  pullPolicy: Always
  tag: latest

persistence:
  config:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    retain: true
    size: 100Mi
    globalMounts:
      - path: /config
        readOnly: false
  data:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    retain: true
    globalMounts:
      - path: /data
        readOnly: false
    size: 10Gi

defaultPodOptions:
  securityContext:
    fsGroup: 1000
    fsGroupChangePolicy: Always

controllers:
  main:
    type: statefulset
    containers:
      main:
        # templated from main values `images` section
        image: {}
        securityContext:
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000

service:
  main:
    type: ClusterIP
    controller: main
    ports:
      http:
        port: 8112
        protocol: TCP
      rtc:
        port: 58846
        protocol: TCP
  torrent:
    type: ClusterIP
    controller: main
    ports:
      tcp:
        port: 51416
        protocol: UDP
      udp:
        port: 51416
        procotol: TCP
