#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
#

image: 
  repository: divadsn/deluge-ltconfig
  pullPolicy: Always
  tag: latest@sha256:eabbf47cf796f3178a10578b6463bcf84fa67fe73716c0e6416cf17b57889363

persistence:
  config:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    retain: true
    size: 100Mi
    globalMounts:
      - path: /config
        readOnly: false
  data:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    retain: true
    globalMounts:
      - path: /data
        readOnly: false
    size: 10Gi

defaultPodOptions:
  securityContext:
    fsGroup: 101
    fsGroupChangePolicy: Always

controllers:
  main:
    type: statefulset
    containers:
      main:
        # templated from main values `images` section
        image: {}
        command:
          - sh
          - '-c'
          - >-
            if [ ! -d "/config/plugins" ]; then
            cp -r /usr/share/deluge/plugins /config/plugins ;
            else
            rm -f /config/plugins/ltConfig-*.egg ;
            cp /usr/share/deluge/plugins/ltConfig-*.egg /config/plugins ;
            fi ;
            run_deluge.sh
        securityContext:
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 101
          runAsGroup: 101

service:
  main:
    type: ClusterIP
    controller: main
    ports:
      http:
        port: 8112
        protocol: HTTP
      rtc:
        port: 58846
        protocol: TCP
  torrent:
    type: ClusterIP
    controller: main
    ports:
      tcp:
        port: 6881
        protocol: TCP
      udp:
        port: 6881
        procotol: UDP
