{{/* Preprocess values and prepare config file */}}
{{- define "ejabberd.preprocess" -}}
controllers:
  main:
    containers:
      main:
        image:
          {{- toYaml .Values.image | nindent 10 }}

configMaps:
  config:
    data:
      {{- range $name, $cfg := .Values.configs }}
      {{ quote $name }}: |-
        {{- toYaml $cfg | nindent 8 }}
      {{- end }}
{{- end -}}
{{- $_ := merge .Values (include "ejabberd.preprocess" . | fromYaml) -}}

{{/* Render the templates */}}
{{- include "bjw-s.common.loader.all" . }}
