{{/* Preprocess values and prepare config file */}}
{{- include "bjw-s.common.loader.init" . }}
{{- define "ejabberd.preprocess" -}}
controllers:
  main:
    containers:
      main:
        image:
          {{- toYaml .Values.image | nindent 10 }}

persistence:
  {{- $dot := . }}
  {{- range $name, $v := .Values.certificates }}
  {{- if dig "enabled" true $v }}
  {{- printf "%s-cert" $name | nindent 2 }}:
    type: secret
    name: {{ include "bjw-s.common.lib.chart.names.fullname" $dot }}-{{ $name }}-cert
    globalMounts:
      - path: /home/ejabberd/conf/certs/{{ $name }}
        readOnly: true
  {{- end }}
  {{- end }}

configMaps:
  config:
    data:
      {{- range $name, $cfg := .Values.configs }}
      {{ quote $name }}: |-
        {{- toYaml $cfg | nindent 8 }}
      {{- end }}


{{- end -}}
{{- $_ := merge .Values (include "ejabberd.preprocess" . | fromYaml) -}}

{{/* Render the templates */}}
{{- include "bjw-s.common.loader.all" . }}
