{{/* Preprocess values and prepare config file */}}
{{- define "dockerhubrss.preprocess" -}}
controllers:
  main:
    containers:
      main:
        image:
          {{- toYaml .Values.image | nindent 10 }}
{{- end -}}
{{- $_ := merge .Values (include "dockerhubrss.preprocess" . | fromYaml) -}}

{{/* Render the templates */}}
{{- include "bjw-s.common.loader.all" . }}
