{{- include "bjw-s.common.loader.init" . }}
{{- $dot := . }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}
  labels:
    {{- include "bjw-s.common.lib.metadata.allLabels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      {{- range $name, $v := .Values.domains }}
      {{- if dig "enabled" true $v }}
      - {{ include "bjw-s.common.lib.chart.names.fullname" $dot }}-{{ replace "." "-" $name }}-cert
      {{- end }}
      {{- end }}
    verbs:
      - get
      - update
      - patch
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}
  labels:
    {{- include "bjw-s.common.lib.metadata.allLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}
---
