#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
#

image: 
  repository: mumblevoip/mumble-server
  pullPolicy: Always
  tag: v1.4.287


configVars:
  # Use it to template values into config file (eg. to use helm-secrets for sensitive values)
  # dbDriver: QPSQL

# You can use helm templates here
config: |
  ; Config file source:
  ; https://github.com/mumble-voip/mumble/blob/master/scripts/murmur.ini
  ; Reference for config file:
  ; https://wiki.mumble.info/wiki/Murmur.ini
  
  ; You can reference values from configVars section here like that:
  ; dbDriver={{ .dbDriver }}
  ; This can be very helpful if you want to store your DB password using helm-secrets
  
  database=/data/mumble-server.sqlite
  ;sqlite_wal=0
  ;dbDriver=QMYSQL
  ;dbUsername=
  ;dbPassword=
  ;dbHost=
  ;dbPort=
  ;dbPrefix=murmur_
  ;dbOpts=
  ;dbus=session
  ;dbusservice=net.sourceforge.mumble.murmur
  ice="tcp -h 127.0.0.1 -p 6502"
  ;icesecretread=
  icesecretwrite=
  ;grpc="127.0.0.1:50051"
  ;grpccert=""
  ;grpckey=""
  ;grpcauthorized=""
  ;logfile=murmur.log
  ;pidfile=
  welcometext="<br />Welcome to this server running <b>Murmur</b>.<br />Enjoy your stay!<br />"
  ;welcometextfile=
  port=64738
  ;host=
  serverpassword=
  bandwidth=558000
  ;timeout=30
  users=100
  ;usersperchannel=0
  messageburst=5
  messagelimit=1
  ; pluginmessagelimit=1
  ; pluginmessageburst=5
  allowping=true
  ;opusthreshold=100
  ;channelnestinglimit=10
  ;channelcountlimit=1000
  ;channelname=[ \\-=\\w\\#\\[\\]\\{\\}\\(\\)\\@\\|]+
  ;username=[-=\\w\\[\\]\\{\\}\\(\\)\\@\\|\\.]+
  ;defaultchannel=0
  ;rememberchannel=true
  ;rememberchannelduration=0
  ;textmessagelength=5000
  ;imagemessagelength=131072
  ;allowhtml=true
  ;logdays=31
  ;registerName=Mumble Server
  ;registerPassword=secret
  ;registerUrl=http://www.mumble.info/
  ;registerHostname=
  ;registerLocation=
  ;bonjour=true
  ;sslCert=
  ;sslKey=
  ;sslPassPhrase=
  ;sslCA=
  ;sslDHParams=@ffdhe2048
  ;sslCiphers=EECDH+AESGCM:EDH+aRSA+AESGCM:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA
  ;uname=
  ;obfuscate=false
  ;certrequired=false
  ;sendversion=true
  ;suggestVersion=
  ;suggestPositional=
  ;suggestPushToTalk=
  ;legacypasswordhash=false
  ;kdfiterations=-1
  ;autobanAttempts=10
  ;autobanTimeframe=120
  ;autobanTime=300
  ;autobanSuccessfulConnections=true
  ;loggroupchanges=false
  ;logaclchanges=false
  ; allowRecording=true
  ; listenersperchannel=5
  ; listenersperuser=2
  ; forceExternalAuth=false
  
  ; You can configure any of the configuration options for Ice here. We recommend
  ; leave the defaults as they are.
  ; Please note that this section has to be last in the configuration file.
  ;
  [Ice]
  Ice.Warn.UnknownProperties=1
  Ice.MessageSizeMax=65536



defaultPodOptions:
  securityContext:
    fsGroup: 1000
    fsGroupChangePolicy: Always

secrets:
  config:
    stringData: {}
      # murmur.ini is autogenerated from `config` string

controllers:
  main:
    type: statefulset
    containers:
      main:
        # templated from main values `images` section
        image: {}
        env:
          - name: MUMBLE_CUSTOM_CONFIG_FILE
            value: /etc/mumble/config.ini
        securityContext:
          capabilities:
            drop:
              - ALL

          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000

service:
  main:
    type: ClusterIP
    controller: main
    ports:
      voice:
        port: 64738
        protocol: UDP
      signaling:
        port: 64738
        procotol: TCP

persistence:
  config:
    type: secret
    identifier: config
    globalMounts:
      - path: /etc/mumble/config.ini
        readOnly: true
        subPath: murmur.ini
  data:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    retain: true
    globalMounts:
      - path: /data
        readOnly: false
    size: 100Mi
