#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
#

controllers:
  main:
    strategy: RollingUpdate
    containers:
      main:
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 999
          runAsGroup: 999
        image:
          repository: pretalx/standalone
          tag: v2024.3.1
          pullPolicy: Always

service:
  main:
    type: ClusterIP
    controller: main
    ports:
      http:
        port: 80
        protocol: HTTP

ingress:
  main:
    enabled: false
    annotations: {}
    hosts: []
    # - host: pretalx.example.com
    #  paths:
    #     - path: /
    #       service:
    #         identifier: main
    #         port: http
    tls: []
    # - secretName: pretalx-cert
    #   hosts:
    #     - pretalx.example.com

# persistence:
#   etc:
#     type: persistentVolumeClaim
#     accessMode: ReadWriteOnce
#     retain: true
#     globalMounts:
#       - path: /etc/searxng
#         readOnly: false
#     size: 1Gi

valkey:
  enabled: true
  architecture: standalone
  # auth:
  #  password: # Set this to avoid regenerating credentials on each install/upgrade
  master:
    persistence:
      enabled: false

postgresql:
  enabled: true
  # auth:
  #   postgresPassword: # Set this to avoid regenerating credentials on each install/upgrade
